### ISSUE TITLE
Tests execution maintain threads up

### ISSUE THREAD

**Issue by guillain** [bernard357/shellbot#19]
When tests are executed the threads remain up& running on the OS.

By full run, total of 42 threads:
[root@10-240-200-11 shellbot]# ps aux | grep -c pyth
42
[root@10-240-200-11 shellbot]#

**Comment by guillain** [comment]
Still the same issue with the new version but need more time to finalize the test to update following the big core update.
to follow...

**Comment by bernard357** [comment]
Same issue here on macOS. The number of processes reported by ``ps aux`` augments significantly after each ``make test``. After some time, the operating system can not create processes anymore, and the computer has to be rebooted. The root cause is not shellbot, but bugs in the basic framework of python itself, when you launch ``python setup.py test``.  Hopefully, shellbot is configured for ``tox`` as an alternate testing framework. So the trick is to use the command ``make test-all``, since this launches ``tox`` and will not pollute your system with zombie processes. Can you confirm that it works as expected on your machine? Thanks

**Comment by guillain** [comment]
Thanks.
