### ISSUE TITLE
Add option display in Menu rich content

### ISSUE THREAD

**Issue by guillain** [bernard357/shellbot#25]
When Menu rich content is used for the question, no option is display.

An adaption of the current code can do that:
```bash
    def ask(self):
        """
        Asks which menu option to select

        If a bare question is provided, then text is added to list
        all available options.

        If a rich question is provided, then we assume that it also
        contains a representation of menu options and displays it 'as-is'.

        """
        text = self.question if self.question else None
        if text:
            index = 1
            text += '\n'
            for option in self.options:
                text += u"{}. {}\n".format(index, option)
                index += 1
            self.bot.say(text)

        content = self.question_content if self.question_content else None
        if content:
            index = 1
            content += '\n'
            for option in self.options:
                content += u"{}. {}\n".format(index, option)
                index += 1
            self.bot.say(' ',content=content)

        self.start_time = time.time()
        self.listen()
```
Thanks ;)

**Comment by bernard357** [comment]
Guillain, it is not sure that you can handle ``content``like you do for ``text``. We all know what text is made of lines separated by newlines. So it is easy to join some options with newlines and send that to the chat space. On the other hand, content can be Markdown or HTML, or any similar rich format. The issue is that except for Markdown, you cannot assume that newlines are appropriate for formatting. Specially, if the content is based on HTML, you would use some tags like ``<ul>``,  ``<li>``, etc. Because of this, shellbot transmit content as-is most of the time, but do not change it.

So, at the end of the day, the trick is to format options in ``question_content`` before this is given to the menu instance. For example in Markdown:

```
menu = Menu(question="Where do you want to go?",
            options=["I want to go North", "Actually, South would be better"],
            question_content="**Where do you want to go?**\n1. I want to go _North_\n2. Actually, _South_ would be better")
```

Or, the equivalent in HTML:

```
menu = Menu(question="Where do you want to go?",
            options=["I want to go North", "Actually, South would be better"],
            question_content="<h3>Where do you want to go?</h3><ol><li>I want to go North</li><li>Actually, South would be better</li></ol>")
```
At the end of the day, we want that shellbot deals blindly with rich content. Does it make sense?

**Comment by guillain** [comment]
I got it. Thanks
