### ISSUE TITLE
Shellbot cmd KO during Input/Menu acquisition

### ISSUE THREAD

**Issue by guillain** [bernard357/shellbot#26]
If shellbot command is executed during the Input or Menu machine acquisition included in Step and Sequence, the shellbot command is not recognized.

It's activate again when the sequences of the step are done.

**Comment by bernard357** [comment]
Guillain, the behavior of shellbot has changed. This is because in direct channels there is no way to distinguish text that is sent explicitly to the bot from text that is the input itself. Now during the capture sequence, all text typed by the end user is considered as input. A consequence of this change is that you cannot submit a shell command while the bot is expecting some input. Are you ok with this approach?

**Comment by guillain** [comment]
This must be taken into account when we imagine and create the scenario. Thanks for the info
